version: '3'
services:
  api:
    image: mikaelle2rubia/sistemagrupbras:latest
    ports:
      - "8080:8080"
    depends_on:
      - local-postgres-compose
      
  local-postgres-compose:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "grupobrasileirodeploy"
    ports:
     - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
networks:
  postgres-compose-network:
    driver: bridge