name: Deploy Application

on:
    push:
        branches: [deploy-cepedi]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Java 
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '17'
            - name: Build project
              run: mvn clean install -DskipTests
            - name: Login Deploy Hub
              run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
            - name: Build docker image
              run: docker build -t mikaelle2rubia/springservice .
            - name: Push docker image
              run: docker push mikaelle2rubia/springservice
              
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull Docker Image
              run: docker pull mikaelle2rubia/springservice:latest
            - name: Remove Docker Container
              run: docker rm -f grupobrasileirodeploy
            - name: Run Docker Container
              run: docker run -d -p 8081:8080 -e DATABASE_USER=${{secrets.DATABASE_USER}} -e DATABASE_PASSWORD='${{secrets.DATABASE_PASSWORD}}' -e DATABASE_URL=${{secrets.DATABASE_URL}} --name grupobrasileirodeploy mikaelle2rubia/springservice